version: "2"
services:
  app:
    image: graphcool/scala-sbt-docker
    links:
    - test-db
    - rabbit
    environment:
      SQL_CLIENT_HOST: "test-db"
      SQL_CLIENT_PORT: "5432"
      SQL_CLIENT_USER: "root"
      SQL_CLIENT_PASSWORD: "graphcool"
      RABBITMQ_URI: "amqp://rabbit"
      GLOBAL_RABBIT_URI: "amqp://rabbit"
      BUGSNAG_API_KEY: ""
      CLUSTER_ADDRESS: "http://localhost:9000"
      SCHEMA_MANAGER_SECRET: "empty"
      PACKAGECLOUD_PW: "${PACKAGECLOUD_PW}"
      CLUSTER_VERSION: "latest"
      COMMIT_SHA: "123abcd"
    volumes:
      - ../../..:/root
      - ~/.ivy2:/root/.ivy2
      - ~/.coursier:/root/.coursier
    working_dir: /root/server

#  test-db:
#    image: mysql:5.7
#    command: mysqld --max-connections=1000 --sql-mode="ANSI,ALLOW_INVALID_DATES,ANSI_QUOTES,ERROR_FOR_DIVISION_BY_ZERO,HIGH_NOT_PRECEDENCE,IGNORE_SPACE,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_BACKSLASH_ESCAPES,NO_ENGINE_SUBSTITUTION,NO_KEY_OPTIONS,NO_UNSIGNED_SUBTRACTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,PIPES_AS_CONCAT,REAL_AS_FLOAT,STRICT_ALL_TABLES,STRICT_TRANS_TABLES,TRADITIONAL"
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: graphcool
#      MYSQL_USER: root
#      MYSQL_DATABASE: graphcool
#      MYSQL_PASSWORD: graphcool
#    ports:
#      - "3306"
#
  test-db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "graphcool"
    ports:
      - "5432"

  rabbit:
    image: rabbitmq:3.7.2-management
    restart: always
    hostname: rabbit-host
    ports:
      - "5672:5672"
      - "15672:15672"

  ping-db:
    image: mysql:5.7
    command: echo "Just used from test.sh"
    links:
    - test-db
    environment:
      MYSQL_PWD: graphcool
