# Transient db - will lose it's data once restarted
version: "3"
services:
  postgres:
    image: postgres:10.3
    container_name: psql
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_USER: $SQL_CLIENT_USER
      POSTGRES_PASSWORD: $SQL_CLIENT_PASSWORD
    ports:
      - "127.0.0.1:${SQL_CLIENT_PORT}:5432"