steps:
  - label: ":scala: libs"
    command: cd server && ./scripts/test.sh libs

  - label: ":scala: subscriptions"
    command: cd server && ./scripts/test.sh subscriptions

  - label: ":scala: deploy"
    command: cd server && ./scripts/test.sh deploy

  - label: ":scala: api"
    command: cd server && ./scripts/test.sh api

  - label: ":scala: single-server"
    command: cd server && ./scripts/test.sh single-server

  - wait

  - label: ":docker: Build"
    command: ./server/scripts/docker-build.sh
    branches: graphql-database

  - wait

  - label: ":llama: Deploy"
    command: ./server/scripts/beta_deploy.sh
    branches: graphql-database
