steps:
  - label: ":scala: libs"
    command: cd server && ./scripts/test.sh libs

  - label: ":scala: subscriptions"
    command: cd server && ./scripts/test.sh subscriptions

  - label: ":scala: deploy"
    command: cd server && ./scripts/test.sh deploy

  - label: ":scala: api"
    command: cd server && ./scripts/test.sh api

  - label: ":scala: images"
    command: cd server && ./scripts/test.sh images

  - wait

  - label: ":docker: Build and deploy DEV"
    command: ./server/scripts/docker-build-and-deploy.sh db-beta-ew1-dev-2
    branches: master
