projects:
  db:
    schemaPath: src/generated/prisma.graphql
    extensions:
      endpoints:
        default: http://localhost:4466/hooks
      prisma: prisma.yml
      codegen:
        output:
          typings: src/generated/prisma.ts
        generator: typegen
        language: typescript
