# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
workflows:
  version: 2
  build-dev:
    jobs:
      build:
        filters:
          branches:
            only: /dev/
        docker:
          # specify the version you desire here
          - image: circleci/node:7.10
          
          # Specify service dependencies here if necessary
          # CircleCI maintains a library of pre-built images
          # documented at https://circleci.com/docs/2.0/circleci-images/
          # - image: circleci/mongo:3.4.4

        working_directory: ~/repo

        steps:
          - run: yarn global add docs-cli
          - run:
            name: Deploy content to dev
            command: ./scripts/deploy.sh
            environment:
              BLUE_ID: 'cj67nv8do36px0187fa6i2n6z'
              GREEN_ID: 'cj6glidms1ego0162chqa3al4'

  build-master:
    jobs:
      build:
        filters:
          branches:
            only: /master/
        docker:
          # specify the version you desire here
          - image: circleci/node:7.10
          
          # Specify service dependencies here if necessary
          # CircleCI maintains a library of pre-built images
          # documented at https://circleci.com/docs/2.0/circleci-images/
          # - image: circleci/mongo:3.4.4

        working_directory: ~/repo

        steps:
          - run: yarn global add docs-cli
          - run:
            name: Deploy content to production
            command: ./scripts/deploy.sh
            environment:
              BLUE_ID: 'cj67nv8do36px0187fa6i2n6z'
              GREEN_ID: 'cj6glidms1ego0162chqa3al4'
