jobs:
  # CLI publishing
  cli:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: cd cli && yarn
      - run: ./cli/scripts/publish.sh

  # content deployment
  content:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo npm i -g @graphcool/docs-cli
      - run:
          command: .circleci/deploy-docs.sh || .circleci/deploy-docs.sh
          environment:
            BLUE_ID: cjce1hjzi0z1o01539nc8949x
            GREEN_ID: cjce1bhux0xwx0127k0ava9o4
            ALIAS: prisma-docs

workflows:
  version: 2
  build:
    jobs:
      - cli:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
      - content:
          filters:
            branches:
              only:
                - master
