projects:
  app: 
    schemaPath: server/schema.graphql
    extensions:
      endpoints:
        default: 'http://localhost:4000'
  db: 
    schemaPath: server/generated-schema.graphql
    extensions:
      prisma: prisma/prisma.yml
