language: node_js
node_js:
  - "8"

services:
  - docker

install:
  - npm install

script:
  - docker-compose up -d
  - docker ps
  - sleep 20
  - ./node_modules/.bin/prisma deploy
  - ./node_modules/.bin/graphql get-schema --project db
  - ./node_modules/.bin/graphql codegen
  - npm run test