# Transient db - will lose it's data once restarted
version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "127.0.0.1:27017:27017"
