projects:
  db:
    schemaPath: src/generated/prisma.graphql
    extensions:
      endpoints:
        default: http://localhost:4466/yml-structure
      prisma: prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
