projects:
  db:
    schemaPath: generated-schema.graphql
    extensions:
      endpoints:
        default: 'http://localhost:4466/yaml-structure'
      prisma: prisma.yml
      prepare-binding:
        output: generated-prisma.ts
        generator: prisma-ts
