projects:
  app:
    schemaPath: src/schema/schema.graphql
    extensions:
      endpoints:
        default: 'http://localhost:4000'
  db:
    schemaPath: src/generated/generated-schema.graphql
    extensions:
      endpoints:
        default: 'http://localhost:4466/application-server'
